name: calculator
description: Calculator App.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true